# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end



  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :beta do
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(
      track:'beta',
      version_code:4,
      version_name:'3.0.1',
      aab: "/Users/JsonDev/Developer/lista-de-entrega-barcode/build/app/outputs/bundle/release/app-release.aab",
    
    )
    send_message_slack
  end

  desc "Validate Play Store Key"
  lane :validate_key do
    validate_play_store_json_key(
      json_key: '/Users/JsonDev/Downloads/fastlane-supply-key/GooglePlayConsole-IAM.json'
    )
  end

  desc "Sand a message to slack"
  lane :send_message_slack do
    slack(
      message: "App successfully uploaded.",
      slack_url: ENV['SLACK_WEBHOOK']
    )
  end
end
