
name: Flutter

on:
  pull_request:

jobs:
  build:
    environment: development
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
      - run: flutter pub get
      - name: Setup Symfony
        working-directory: ./android
        run: |
          fastlane send_message_slack
          env: 
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            
