
name: PR Changes

on:
  pull_request:
   
jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
      - run: dart pub global activate arb_utils
      - run: flutter pub get
      - run: flutter clean
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter gen-l10n && arb_utils sort lib/l10n/app_en.arb

